owner: nguyenvanthi
repo: uptime

sites:
  - name: "[Trio UAT] User Service"
    url: https://user.uat.s2tek.net/health
  - name: "[Trio UAT] Gateway Service"
    url: https://gateway.uat.s2tek.net/health
  - name: "[Trio UAT] CMS Client"
    url: https://cms.uat.s2tek.net/
  - name: "[Trio Stable] User Service"
    url: https://user-service.trio.s2tek.net/health
  - name: "[Trio Stable] Gateway Service"
    url: https://gateway-service.trio.s2tek.net/health
  - name: "[Trio Stable] CMS Client"
    url: https://cms-client.trio.s2tek.net/
  - name: "[S2tek Stable] FS Server"
    url: https://fishing-card-server.s2tek.net/health
  - name: "[S2tek Stable] FS Client"
    url: https://fishing-card-client.s2tek.net
  - name: "[NAS] Synology"
    url: https://nas.s2tek.net
    
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
