owner: nguyenvanthi
repo: uptime

sites:
  - name: "[Trio Beta] User Service"
    url: https://user-service.uat.s2tek.net/health
  - name: "[Trio Beta] Gateway Service"
    url: https://gateway-service.uat.s2tek.net/health
  - name: "[Trio Beta] CMS Client"
    url: https://cms-client.uat.s2tek.net/
  - name: "[Trio Alpha] User Service"
    url: https://user-service.trio.s2tek.net/health
  - name: "[Trio Alpha] Gateway Service"
    url: https://gateway-service.trio.s2tek.net/health
  - name: "[Trio Alpha] CMS Client"
    url: https://cms-client.trio.s2tek.net/
  - name: "[S2tek Alpha] FS Server"
    url: https://fishing-card-server.s2tek.net/health
  - name: "[S2tek Alpha] FS Client"
    url: https://fishing-card-client.s2tek.net
  - name: "[DevOps] Synology"
    url: https://nas.s2tek.net
  - name: "[DevOps] Prometheus"
    url: https://prometheus.s2tek.net/status
    
status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
